# Build and deploy to pages
name: Build movie pages
concurrency:
  cancel-in-progress: true
  group: "pages"
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup NPM
      uses: actions/setup-node@v6
      with:
        check-latest: false
        node-version: "25.9.0"
    - name: Build with NPM
      run: npm ci && npm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
